services:
  ollama:
    image: ollama/ollama
    container_name: manzolo-ollapdf-ollama
    ports:
      - "11434:11434"
    volumes:
      - ./ollama_data:/root/.ollama
    networks:
      - ollapdf-net

  ollapdf:
    depends_on:
      - ollama
