services:
  ollapdf:
    build: .
    container_name: manzolo-ollapdf-rag
    ports:
      - "8501:8501"
    volumes:
      - ./data:/app/data
    environment:
      - OLLAMA_HOST=${OLLAMA_HOST}
      - OLLAMA_MODEL_NAME=${OLLAMA_MODEL_NAME}
      - DEFAULT_TEMPERATURE=${DEFAULT_TEMPERATURE}
      - DEFAULT_CHUNK_SIZE=${DEFAULT_CHUNK_SIZE}
      - DEFAULT_CHUNK_OVERLAP=${DEFAULT_CHUNK_OVERLAP}
      - DEFAULT_TOP_K=${DEFAULT_TOP_K}
    networks:
      - ollapdf-net

networks:
  ollapdf-net: